### ISSUE TITLE
Error: Failed to find 'tailwindcss/components'

### ISSUE THREAD

**Issue by PlainBane** [maizzle/framework#1025]
- Maizzle Version: 4.4.6
- Node.js Version: 20.3.0
- Linux Ubuntu 23.04 / Local dev 

Hi, I'm using pnpm and was getting this error. Solved it by adding this  in package.json.
```
"devDependencies": {
    "tailwindcss": "^3.3.2"
  }
```

```
> maizzle serve
// Also Error: Failed to find 'tailwindcss/components'
✖ Error: Failed to find 'tailwindcss/utilities'
  in [
    /home/user/_Dev/Node/email/src/css
  ]
/home/user/_Dev/Node/email/node_modules/.pnpm/@maizzle+framework@4.4.6_glob@7.2.3/node_modules/@maizzle/framework/src/generators/tailwindcss.js:154
        throw new SyntaxError(error)
              ^

SyntaxError: Error: Failed to find 'tailwindcss/utilities'
  in [
    /home/user/_Dev/Node/email/src/css
  ]
    at /home/user/_Dev/Node/email/node_modules/.pnpm/@maizzle+framework@4.4.6_glob@7.2.3/node_modules/@maizzle/framework/src/generators/tailwindcss.js:154:15
    at async module.exports [as toDisk] (/home/user/_Dev/Node/email/node_modules/.pnpm/@maizzle+framework@4.4.6_glob@7.2.3/node_modules/@maizzle/framework/src/generators/output/to-disk.js:30:7)
    at async build (/home/user/_Dev/Node/email/node_modules/.pnpm/@maizzle+framework@4.4.6_glob@7.2.3/node_modules/@maizzle/framework/src/commands/build.js:11:29)
    at async Object.serve (/home/user/_Dev/Node/email/node_modules/.pnpm/@maizzle+framework@4.4.6_glob@7.2.3/node_modules/@maizzle/framework/src/commands/serve.js:40:3)

Node.js v20.3.0

```

**Comment by wallace-sf** [comment]
I also experienced this error using the official starter kit.
