### ISSUE TITLE
SyntaxError: Failed to find 'tailwindcss/components' (pnpm)

### ISSUE THREAD

**Issue by BeetrootShoulders** [maizzle/framework#1096]
- Maizzle Version: 4.6.1
- Node.js Version: 19.9.0

I get the following error when attempting to run the dev server on a fresh install of Maizzle:

```
✖ Error: Failed to find 'tailwindcss/components'
  in [
    C:\Users\***\Sites\***\src\css
  ]
C:\Users\***\Sites\****\node_modules\.pnpm\@maizzle+framework@4.6.1_glob@7.2.3\node_modules\@maizzle\framework\src\generators\tailwindcss.js:154
        throw new SyntaxError(error)
              ^

SyntaxError: Error: Failed to find 'tailwindcss/components'
  in [
    C:\Users\***\Sites\***\src\css
  ]
    at C:\Users\***\Sites\***\node_modules\.pnpm\@maizzle+framework@4.6.1_glob@7.2.3\node_modules\@maizzle\framework\src\generators\tailwindcss.js:154:15
    at async module.exports [as toDisk] (C:\Users\***\Sites\***\node_modules\.pnpm\@maizzle+framework@4.6.1_glob@7.2.3\node_modules\@maizzle\framework\src\generators\output\to-disk.js:31:7)
    at async build (C:\Users\***\Sites\***\node_modules\.pnpm\@maizzle+framework@4.6.1_glob@7.2.3\node_modules\@maizzle\framework\src\commands\build.js:11:29)
    at async Object.serve (C:\Users\****\Sites\***\node_modules\.pnpm\@maizzle+framework@4.6.1_glob@7.2.3\node_modules\@maizzle\framework\src\commands\serve.js:40:3)
```

I followed the instructions for getting started on the Maizzle site - degit the starter, npm install, npm run dev.

**Comment by cossssmin** [comment]
Could be because of pnpm, not sure why it can't resolve it. Try adding Tailwind as a dependency.

**Comment by BeetrootShoulders** [comment]
Yes, it works if I use npm.

**Comment by davbtmx** [comment]
If you use `pnpm` and experience this problem, add this file to the root of your maizzle project:

`.npmrc`
```
shamefully-hoist=true
```

Then reinstall the dependencies via `pnpm install`.

This should fix the problem as it did for me.
