### ISSUE TITLE
Markdown Starter throws fast-glob TypeError

### ISSUE THREAD

**Issue by mheiduk** [maizzle/framework#1409]
- Maizzle Version: 5.0.0
- Node.js Version: 22.12.0
- MacOS Version: 15.2

I've installed the latest Maizzle version and followed the installation wizard with the Markdown Starter preset. Running `npm run dev` outputs the following error:

```
> dev
> maizzle serve

◐ Starting server.../Users/xxx/Developer/maizzle/node_modules/fast-glob/out/index.js:99
        throw new TypeError('Patterns must be a string (non empty) or an array of strings');
              ^

TypeError: Patterns must be a string (non empty) or an array of strings
    at assertPatternsInput (/Users/xxx/Developer/maizzle/node_modules/fast-glob/out/index.js:99:15)
    at AsyncFunction.FastGlob (/Users/xxx/Developer/maizzle/node_modules/fast-glob/out/index.js:9:5)
    at getTemplatePaths (file:///Users/xxx/Developer/maizzle/node_modules/@maizzle/framework/src/server/index.js:53:19)
    at getUpdatedRoutes (file:///Users/xxx/Developer/maizzle/node_modules/@maizzle/framework/src/server/index.js:57:10)
    at default (file:///Users/xxx/Developer/maizzle/node_modules/@maizzle/framework/src/server/index.js:140:25)
    at async Command.<anonymous> (file:///Users/xxx/Developer/maizzle/node_modules/@maizzle/cli/src/index.js:98:40)
    at async Command.parseAsync (/Users/xxx/Developer/maizzle/node_modules/commander/lib/command.js:1092:5)

Node.js v22.12.0
```

It seems like that the Markdown Starter wasn't migrated yet to v5?

**Comment by cossssmin** [comment]
Yes, need to update it to v5, sorry about that. Will try to get it done today 👍

**Comment by cossssmin** [comment]
The starter is now updated for v5, thanks for reporting!

https://github.com/maizzle/starter-markdown

**Comment by OliverGrimsley** [comment]
How do you implement this? I had a v4 in my app, upgraded to v5, and I get the error below (I deleted node_modules, and the lock file and rebuilt - no effect)

```
npm run dev         

> dev
> maizzle serve

◐ Starting server.../Users/[privacy omitted]/maizzle/node_modules/fast-glob/out/index.js:99
        throw new TypeError('Patterns must be a string (non empty) or an array of strings');
              ^

TypeError: Patterns must be a string (non empty) or an array of strings
    at assertPatternsInput (/Users/[privacy omitted]/maizzle/node_modules/fast-glob/out/index.js:99:15)
    at AsyncFunction.FastGlob (/Users/[privacy omitted]/maizzle/node_modules/fast-glob/out/index.js:9:5)
    at getTemplatePaths (file:///Users/[privacy omitted]/maizzle/node_modules/@maizzle/framework/src/server/index.js:53:19)
    at getUpdatedRoutes (file:///Users/[privacy omitted]/maizzle/node_modules/@maizzle/framework/src/server/index.js:57:10)
    at default (file:///Users/[privacy omitted]/maizzle/node_modules/@maizzle/framework/src/server/index.js:140:25)
    at async Command.<anonymous> (file:///Users/[privacy omitted]/maizzle/node_modules/@maizzle/cli/src/index.js:98:40)
    at async Command.parseAsync (/Users/[privacy omitted]/maizzle/node_modules/commander/lib/command.js:1092:5)
```
