### ISSUE TITLE
UnhandledPromiseRejectionWarning: YAMLException

### ISSUE THREAD

**Issue by nodeg** [maizzle/framework#239]
- Maizzle Version: 1.2.0
- Node.js Version: 14.4.0 / 12.18.1

I did a `npm install` today and got the following message when developing with Maizzle.
```bash
$ maizzle serve
⠴ Building emails...(node:11361) UnhandledPromiseRejectionWarning: YAMLException: can not read a block mapping entry; a multiline key may not be an implicit key at line 2, column 1:
    
    ^
    at generateError (/home/dom/git/testing/node_modules/js-yaml/lib/js-yaml/loader.js:167:10)
    at throwError (/home/dom/git/testing/node_modules/js-yaml/lib/js-yaml/loader.js:173:9)
    at readBlockMapping (/home/dom/git/testing/node_modules/js-yaml/lib/js-yaml/loader.js:1073:9)
    at composeNode (/home/dom/git/testing/node_modules/js-yaml/lib/js-yaml/loader.js:1359:12)
    at readDocument (/home/dom/git/testing/node_modules/js-yaml/lib/js-yaml/loader.js:1525:3)
    at loadDocuments (/home/dom/git/testing/node_modules/js-yaml/lib/js-yaml/loader.js:1588:5)
    at load (/home/dom/git/testing/node_modules/js-yaml/lib/js-yaml/loader.js:1614:19)
    at safeLoad (/home/dom/git/testing/node_modules/js-yaml/lib/js-yaml/loader.js:1637:10)
    at parse (/home/dom/git/testing/node_modules/front-matter/index.js:64:20)
    at extractor (/home/dom/git/testing/node_modules/front-matter/index.js:26:12)
(Use `node-default --trace-warnings ...` to show where the warning was created)
(node:11361) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:11361) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
⠧ Building emails...
```

The command never finishes.
I am aware of the fact that it has to be related to `js-yaml`, but I think it is still important here, since Maizzle does not work anymore.

```bash
$ npm ls js-yaml
/home/dom/git/beta-emails-testing
└─┬ @maizzle/framework@1.2.0
  └─┬ front-matter@4.0.2
    └── js-yaml@3.14.0 
``` 

Any suggestions? Can you reproduce the error?

**Comment by nodeg** [comment]
The error was related to some merging error. Sorry for bothering.
