### ISSUE TITLE
Maizzle Proxy Settings

### ISSUE THREAD

**Issue by benbabics** [maizzle/framework#281]
- Maizzle Version: 1.0.2
- Node.js Version: 10.9.0

Sitting behind a proxy for work and would like to use Maizzle to create HTML Emails. Are there proxy settings for Maizzle? 

Below is the output while trying to use a starter:

```
> maizzle new amp4email
⠏ Crafting new Maizzle project in /Users/user/Sites/smartauction/starter-amp4email...(node:5876) UnhandledPromiseRejectionWarning: Error: Command failed with exit code 128: git clone https://github.com/maizzle/starter-amp4email.git starter-amp4email --single-branch
Cloning into 'starter-amp4email'...
fatal: unable to access 'https://github.com/maizzle/starter-amp4email.git/': LibreSSL SSL_connect: SSL_ERROR_SYSCALL in connection to github.com:443
    at makeError (/Users/user/.nvm/versions/node/v10.9.0/lib/node_modules/@maizzle/cli/node_modules/execa/lib/error.js:59:11)
    at handlePromise (/Users/user/.nvm/versions/node/v10.9.0/lib/node_modules/@maizzle/cli/node_modules/execa/index.js:114:26)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:5876) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:5876) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the⠏ Crafting new Maizzle project in /Users/user/Sites/smartauction/starter-amp4email...
```

**Comment by cossssmin** [comment]
The CLI simply runs a `git clone` [command](https://github.com/maizzle/cli/blob/master/src/commands/new.js#L64), do you have Git configured to use that proxy?

You can also create a project based on a starter manually:

```sh
# clone the repo
git clone https://github.com/maizzle/starter-amp4email.git starter-amp4email

# change current directory
cd starter-amp4email

# remove Git files
rm -rf .git .github

# install dependencies
npm i
```
