### ISSUE TITLE
Suggestion: Lazy Init Browsersync

### ISSUE THREAD

**Issue by digitalmaster** [maizzle/framework#605]
- Maizzle Version: 3.7.2
- Node.js Version: 12.22.9

First of all, thank you for putting together a truly remarkable project. 👏 

### Issue
I'm using Maizzle in a NextJS serverless function hosted on their Vercel environment. I'm using the [Node Render](https://maizzle.com/docs/nodejs/) function to dynamically render and send HTML emails. Locally I had no issues, however as soon as I deployed to Vercel's serverless function environment I started getting this error:
```bash
Error: ENOENT: no such file or directory, open '/var/task/curriculum/curriculum/node_modules/browser-sync-ui/lib/plugins/sync-options/sync-options.html'
    at Object.openSync (fs.js:462:3)
    at Object.readFileSync (fs.js:364:35)
    at fileContent (/var/task/curriculum/curriculum/node_modules/browser-sync-ui/lib/plugins/sync-options/sync-options.plugin.js:65:26)
    at Object.<anonymous> (/var/task/curriculum/curriculum/node_modules/browser-sync-ui/lib/plugins/sync-options/sync-options.plugin.js:45:19)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18) {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: '/var/task/curriculum/curriculum/node_modules/browser-sync-ui/lib/plugins/sync-options/sync-options.html'
}
```
I was able to confirm that Vercel was somehow pruning these files from the `node_modules` folder. My hypothesis is that it has something to do with [this](https://nextjs.org/docs/advanced-features/output-file-tracing).

After spending some trying and failing to get Vercel to not purge these files, I started to see if I could figure out why Browsersync was trying to run in production in the first place. I was able to track it down to this line: https://github.com/maizzle/framework/blob/a0e41c0ba104f925ceda02192f5bb5f90785638e/src/index.js#L5

To validate this hypothesis, I reproduced the production error locally by deleting the files in `node_modules/browser-sync-ui/lib/plugins/sync-options/` and triggering Maizzle.render. I then made the following patch (this [patched](https://www.npmjs.com/package/patch-package) module is now running fine in production):
```patch
diff --git a/node_modules/@maizzle/framework/src/index.js b/node_modules/@maizzle/framework/src/index.js
index f258852..f87105a 100644
--- a/node_modules/@maizzle/framework/src/index.js
+++ b/node_modules/@maizzle/framework/src/index.js
@@ -2,7 +2,6 @@ const ora = require('ora')
 const path = require('path')
 const fs = require('fs-extra')
 const {get, merge} = require('lodash')
-const bs = require('browser-sync').create()
 const Config = require('./generators/config')
 const Output = require('./generators/output')
 const transformers = require('./transformers')
@@ -10,6 +9,15 @@ const {clearConsole} = require('./utils/helpers')
 const Plaintext = require('./generators/plaintext')
 const Tailwind = require('./generators/tailwindcss')
 
+const getBrowserSync = () => {
+  if(!global.cachedBrowserSync) {
+    const bs = require('browser-sync')
+    global.cachedBrowserSync = bs.create()
+  }
+
+  return global.cachedBrowserSync
+}
+
 const self = module.exports = { // eslint-disable-line
   ...transformers,
   render: async (html, options) => Output.toString(html, options),
@@ -66,7 +74,7 @@ const self = module.exports = { // eslint-disable-line
         const spinner = ora()
 
         // Watch for Template file changes
-        bs.watch(templatePaths)
+        getBrowserSync().watch(templatePaths)
           .on('change', async file => {
             clearConsole()
 
@@ -115,25 +123,25 @@ const self = module.exports = { // eslint-disable-line
               .render(await fs.readFile(file, 'utf8'), renderOptions)
               .then(({html, config}) => fs.outputFile(config.permalink || finalDestination, html))
               .then(() => {
-                bs.reload()
+                getBrowserSync().reload()
                 spinner.succeed(`Compiled in ${(Date.now() - start) / 1000}s [${file}]`)
               })
               .catch(() => spinner.warn(`Received empty HTML, please save your file again [${file}]`))
           })
 
         // Watch for changes in all other files
-        bs.watch(globalPaths, {ignored: templatePaths})
-          .on('change', () => self.build(env, config).then(() => bs.reload()))
-          .on('unlink', () => self.build(env, config).then(() => bs.reload()))
+        getBrowserSync().watch(globalPaths, {ignored: templatePaths})
+          .on('change', () => self.build(env, config).then(() => getBrowserSync().reload()))
+          .on('unlink', () => self.build(env, config).then(() => getBrowserSync().reload()))
 
         // Watch for changes in config files
-        bs.watch('config*.js')
+        getBrowserSync().watch('config*.js')
           .on('change', async file => {
             const parsedEnv = path.parse(file).name.split('.')[1] || 'local'
 
             Config
               .getMerged(parsedEnv)
-              .then(config => self.build(parsedEnv, config).then(() => bs.reload()))
+              .then(config => self.build(parsedEnv, config).then(() => getBrowserSync().reload()))
           })
 
         // Browsersync options
@@ -154,10 +162,11 @@ const self = module.exports = { // eslint-disable-line
         }
 
         // Initialize Browsersync
-        bs.init(bsOptions, () => {})
+        getBrowserSync().init(bsOptions, () => {})
       })
       .catch(error => {
         throw error
       })
   }
 }
+
```

Since this worked, I figured I'd reach out here to get some feedback and see if it's worth throwing up a PR for. 

Thanks again for this awesome project 🙏

**Comment by cossssmin** [comment]
Hey, thanks so much for taking the time to investigate this!

I'd love to see a PR, could you do it off of the https://github.com/maizzle/framework/tree/4.0 branch so we get this into Maizzle 4?

**Comment by digitalmaster** [comment]
Sounds good.. will do 👍

**Comment by cossssmin** [comment]
Merged, thanks again for this. I'll close the issue once 4.0 is out 👍

**Comment by digitalmaster** [comment]
Awesome. Thanks a lot @cossssmin! Excellent work on this project. 👏
