### ISSUE TITLE
Build sometimes fails with comments inside of css definition block

### ISSUE THREAD

**Issue by bravecrayon** [maizzle/framework#745]
- Maizzle Version: 4.0.2
- Node.js Version: 14.19.3

Building fails, sometimes, with comments in CSS class definition with `inlineCSS: true` is set, which I obviously want to keep. The work around is easy, just adjust the location of or remove the comment, but wanted to report it anyway.

Error is:

```
⚠ Failed to compile template: template.html
TypeError: Cannot read property 'includes' of undefined
    at <input css mlHLDu>:359:1
    at /Users/bravecrayon/Projects/proj/node_modules/@maizzle/framework/src/transformers/removeInlinedSelectors.js:51:22
    at Array.forEach (<anonymous>)
    at /Users/bravecrayon/Projects/proj/node_modules/@maizzle/framework/src/transformers/removeInlinedSelectors.js:50:34
    at /Users/bravecrayon/Projects/proj/node_modules/posthtml/lib/api.js:91:45
    at traverse (/Users/bravecrayon/Projects/proj/node_modules/posthtml/lib/api.js:105:26)
    at traverse (/Users/bravecrayon/Projects/proj/node_modules/posthtml/lib/api.js:111:5)
    at traverse (/Users/bravecrayon/Projects/proj/node_modules/posthtml/lib/api.js:105:17)
    at Array.match (/Users/bravecrayon/Projects/proj/node_modules/posthtml/lib/api.js:90:7)
    at /Users/bravecrayon/Projects/proj/node_modules/@maizzle/framework/src/transformers/removeInlinedSelectors.js:32:14
    at /Users/bravecrayon/Projects/proj/node_modules/postcss/lib/container.js:96:18 {
  postcssNode: Rule {
    raws: { before: '\n', between: ' ', semicolon: false, after: '\n  ' },
    type: 'rule',
    nodes: [ [Comment] ],
    parent: Root {
      raws: [Object],
      type: 'root',
      nodes: [Array],
      source: [Object],
      lastEach: 1,
      indexes: [Object],
      [Symbol(isClean)]: false,
      [Symbol(my)]: true
    },
    source: { start: [Object], input: [Input], end: [Object] },
    selector: '.foo-class',
    [Symbol(isClean)]: false,
    [Symbol(my)]: true
  }
}
```

The following CSS will cause this error:

```css
.foo-class {
  /* COMMENT */
}
```

```css
.foo-class {
  /* COMMENT */
  color: red;
}
```

However, this compiles without error:
```css
.foo-class {
  color: red;
  /* COMMENT */
}
```

**Comment by cossssmin** [comment]
Yeah I think we need to rethink the way `removeInlinedSelectors` works, as that’s what’s actually causing it and not the actual inlining process.

Meanwhile you could try setting it to `false` in `config.js`, and also change `inlineCSS` to this:

```
inlineCSS: {
  removeStyleTags: true,
}
```

**Comment by cossssmin** [comment]
This should work fine now in 4.1.2, give it a try.

**Comment by bravecrayon** [comment]
Works for me!
