### ISSUE TITLE
urlParameters without _options causing production build to fail

### ISSUE THREAD

**Issue by bravecrayon** [maizzle/framework#771]
- Maizzle Version: 4.2.0
- Node.js Version: 14.19.3

The production build is failing when urlParameters is missing `_options`.

1. Created a new project with the starter `npx degit maizzle/maizzle my-project`. 

2. Added the following to the config:

```
urlParameters: {
  utm_source: 'maizzle'
}
```

3. Build it: `npx maizzle build production`

```
⚠ Failed to compile template: promotional.html
TypeError: Cannot read property 'tags' of undefined
    at module.exports (/Users/homedir/Projects AdHoc/my-project/node_modules/@maizzle/framework/src/transformers/urlParameters.js:10:27)
    at Object.exports.process (/Users/username/Projects AdHoc/my-project/node_modules/@maizzle/framework/src/transformers/index.js:36:16)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async module.exports (/Users/username/Projects AdHoc/my-project/node_modules/@maizzle/framework/src/generators/output/to-string.js:54:12)
    at async /Users/username/Projects AdHoc/my-project/node_modules/@maizzle/framework/src/generators/output/to-disk.js:105:32
    at async asyncForEach (/Users/username/Projects AdHoc/my-project/node_modules/@maizzle/framework/src/utils/helpers.js:4:7)
    at async /Users/username/Projects AdHoc/my-project/node_modules/@maizzle/framework/src/generators/output/to-disk.js:97:11
    at async /Users/username/Projects AdHoc/my-project/node_modules/@maizzle/framework/src/generators/output/to-disk.js:79:7
    at async asyncForEach (/Users/username/Projects AdHoc/my-project/node_modules/@maizzle/framework/src/utils/helpers.js:4:7)
    at async /Users/username/Projects AdHoc/my-project/node_modules/@maizzle/framework/src/generators/output/to-disk.js:71:5
⚠ Failed to compile template: transactional.html
TypeError: Cannot read property 'tags' of undefined
    at module.exports (/Users/username/Projects AdHoc/my-project/node_modules/@maizzle/framework/src/transformers/urlParameters.js:10:27)
    at Object.exports.process (/Users/username/Projects AdHoc/my-project/node_modules/@maizzle/framework/src/transformers/index.js:36:16)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async module.exports (/Users/username/Projects AdHoc/my-project/node_modules/@maizzle/framework/src/generators/output/to-string.js:54:12)
    at async /Users/username/Projects AdHoc/my-project/node_modules/@maizzle/framework/src/generators/output/to-disk.js:105:32
    at async asyncForEach (/Users/username/Projects AdHoc/my-project/node_modules/@maizzle/framework/src/utils/helpers.js:4:7)
    at async /Users/username/Projects AdHoc/my-project/node_modules/@maizzle/framework/src/generators/output/to-disk.js:97:11
    at async /Users/username/Projects AdHoc/my-project/node_modules/@maizzle/framework/src/generators/output/to-disk.js:79:7
    at async asyncForEach (/Users/username/Projects AdHoc/my-project/node_modules/@maizzle/framework/src/utils/helpers.js:4:7)
    at async /Users/username/Projects AdHoc/my-project/node_modules/@maizzle/framework/src/generators/output/to-disk.js:71:5
✔ Built 0 templates in 0.645s
```

It will build successfully if the config is changed to:

```
urlParameters: {
  _options: {},
  utm_source: 'maizzle',
}
```

Also, it fails in the same way if urlParameters is added to the frontmatter without _options.

**Comment by cossssmin** [comment]
Hey thanks for this, will get it sorted shortly! :)
