### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by michalvadak** [maizzle/framework#985]
- @maizzle/framework: 4.4.4
- Node.js Version: 16.13.0

After running `maizzle build en --bin ../../../node_modules/@maizzle/framework/src`

```
✔ Built 2 templates in 0.229s
node:internal/modules/cjs/loader:933
  const err = new Error(message);
              ^

Error: Cannot find module './node_modules/@maizzle/framework/package.json'
Require stack:
- /Users/.../libs/web/email/noop.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at resolveFileName (/Users/.../node_modules/resolve-from/index.js:29:39)
    at resolveFrom (/Users/.../node_modules/resolve-from/index.js:43:9)
    at module.exports (/Users/.../node_modules/resolve-from/index.js:46:47)
    at module.exports (/Users/.../node_modules/import-from/index.js:4:55)
    at module.exports (/Users/.../node_modules/import-cwd/index.js:4:30)
    at Command.<anonymous> (/Users/.../node_modules/@maizzle/framework/node_modules/@maizzle/cli/src/index.js:52:14) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/Users/.../libs/web/email/noop.js' ]
}
```

I've looked into https://github.com/maizzle/framework/issues/974 and https://github.com/maizzle/cli/issues/198 but doesn't managed to get it to work. I have only installed `@maizzle/framework`.

I am using [Nx monorepo](https://nx.dev/).

**Comment by cossssmin** [comment]
Try updating the CLI to 1.5.6 - just released a patch that isolates the update notifier which should fix the issue in monorepos.

https://github.com/maizzle/cli/releases/tag/v1.5.6
