### ISSUE TITLE
Exit with error code when component/single template fails to build

### ISSUE THREAD

**Issue by comatory** [maizzle/framework#986]
- Maizzle Version: #.#.#

4.2.2

- Node.js Version: #.#.#

18.6.0

I have a problem when I build maizzle for production, one of the templates fails because the path to component cannot be found (which is some separate issue). But the problem is the build exits with code 0 (success) but I'd like it to fail so the build system can detect it.

Log:

```
> maizzle build production

⚠ Failed to compile template: key-result-changed.html
Error: [components] The component was not found in /Users/ondrej.synacek/Projects/pb-email-templates/completed-state.html.
    at getComponentPath (/Users/ondrej.synacek/Projects/pb-email-templates/node_modules/posthtml-component/src/index.js:271:15)
    at /Users/ondrej.synacek/Projects/pb-email-templates/node_modules/posthtml-component/src/index.js:176:29
    at /Users/ondrej.synacek/Projects/pb-email-templates/node_modules/posthtml/lib/api.js:85:52
    at traverse (/Users/ondrej.synacek/Projects/pb-email-templates/node_modules/posthtml/lib/api.js:105:26)
    at Array.match (/Users/ondrej.synacek/Projects/pb-email-templates/node_modules/posthtml/lib/api.js:83:7)
    at /Users/ondrej.synacek/Projects/pb-email-templates/node_modules/posthtml-component/src/index.js:169:11
    at /Users/ondrej.synacek/Projects/pb-email-templates/node_modules/posthtml-component/src/index.js:216:38
    at /Users/ondrej.synacek/Projects/pb-email-templates/node_modules/posthtml/lib/api.js:85:52
    at traverse (/Users/ondrej.synacek/Projects/pb-email-templates/node_modules/posthtml/lib/api.js:105:26)
    at traverse (/Users/ondrej.synacek/Projects/pb-email-templates/node_modules/posthtml/lib/api.js:105:17)
✔ Built 26 templates in 3.321s
```

I have `fail: 'verbose'` in my config and I left the `components.strict` undefined so the default is `true` so no error is silenced. Can I make maizzle throw somehow?

**Comment by cossssmin** [comment]
Try removing `fail: verbose`, that just logs it without throwing; by default Maizzle will throw if it can't render a template:

https://github.com/maizzle/framework/blob/d45f1e20af399b0425ded37cf58cf1213f0b4d5b/src/generators/output/to-disk.js#L192-L204
